version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - .:/app/frontend/json
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
